/*
   Upon powering up, the CanSat probe shall collect the required telemetry at a 1 Hz sample
  rate. The telemetry data shall be transmitted with ASCII comma separated fields followed by a
  carriage return in the following format:
  <TEAM ID>,<MISSION TIME>,<PACKET COUNT>,<ALTITUDE>, <PRESSURE>,
  <TEMP>,<VOLTAGE>,<GPS TIME>,<GPS LATITUDE>,<GPS LONGITUDE>,<GPS
  ALTITUDE>,<GPS SATS>,<PITCH>,<ROLL>,<BLADE SPIN RATE>,<SOFTWARE
  STATE>,<BONUS DIRECTION>
*/

unsigned int team_id = 2634;
unsigned int mission_time;
unsigned int packet_count = 0;
float altitude;   //resolution: 0.1 m
float pressure;   //resolution: 0.1 P
float temperature;  //resolution: 0.1 C
float voltage;    //resolution: 0.01 V
int gps_time;     //time generated by gps receiver (in UTC) resolution: 1 s
float gps_latitude; //resolution: 0.0001 degrees
float gps_longitude;  //resolution: 0.0001 degrees
float gps_altitude;   //resolution: 0.1 m
int gps_sats;   //number of gps satellites being tracked by gps receiver (int)
int pitch;    //resolution: 1 degree
int roll;     //resolution: 1 degree
int blade_spin; //resolution: 1 rpm
byte software_state;  //1, 2, 3, 4, 5
float camera_heading;   //resolution: 1 degree

unsigned int start_time;

void setup() {
  // put your setup code here, to run once:
  Serial.begin(9600);
  start_time = millis();
}

void loop() {
  
  //get mission time
  mission_time = millis() - start_time;

  //get packet count
  packet_count++;

  //get altitude
  altitude = 9999.9;

  //get pressure
  pressure = 9999.9;

  //get temperature
  temperature = 9999.9;

  //get battery voltage
  voltage = 9999.99;

  //get gps time;
  gps_time = mission_time;

  //get gps latitude
  gps_latitude = 9999;

  //get gps longitude
  gps_longitude = 9999;

  //get gps altitude
  gps_altitude = 9999;

  //get gps sats
  gps_sats = 4;

  //get pitch
  pitch = 9999;

  //get roll
  roll = 9999;

  //get blade spin rate
  blade_spin = 9999;

  //get software state
  software_state = 2;

  //get heading
  camera_heading = 9999;
  
  
  String message = mission_time + "," +  packet_count + "," + altitude + "," + 
    pressure + "," + temperature + "," + voltage + "," + gps_time + "," + 
    gps_latitude + "," + gps_longitude + "," + gps_altitude + "," + gps_sats + 
    "," + pitch + "," + roll + ", " + blade_spin + "," + software_state + ","
    + camera_heading;
  Serial.print('<');
  Serial.print(message);
  Serial.print('>');

  //wait for handshake from GCS
  if(get_handshake)
}
